searchr_app/urls.py
from django.urls import path
from django.conf.urls import url
from searchr_app import views


app_name = 'searchr_app'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('add_project/', views.AddProjectView.as_view(), name='add_project'),
    path('owner/<slug:username>/project/<slug:slug>/', views.ProjectView.as_view(), name='show_project'),
    path('owner/<slug:username>/project/<slug:slug>/update/', views.UpdateProjectView.as_view(), name='update_project'),
    path('owner/<slug:username>/project/<slug:slug>/<slug:search_slug>/', views.SearchObjectView.as_view(), name='show_search'),
    path('owner/<slug:username>/project/<slug:slug>/<slug:search_slug>/<message>/', views.SearchObjectView.as_view(),
         name='show_search'),
    path('<project_id>/new_search/', views.AddSearchView.as_view(), name='new_search'),
    path('<project_id>/<search_id>/build_query/', views.QueryBuilderView.as_view(), name='query_builder'),
    path('phrase/<phrase_language>/<slug:phrase_slug>/', views.ShowPhraseView.as_view(), name='show_phrase'),
    path('add_phrase/', views.AddPhraseView.as_view(), name='add_phrase'),
    # path('keyword/<keyword_language>/<slug:keyword_slug>/', views.ShowKeywordView.as_view(), name='show_keyword'),
    path('search_result/<search_res_id>', views.ShowSearchResultsView.as_view(), name='search_result'),
    path('search_result/<search_res_id_1>/compare/<search_res_id_2>/', views.CompareSearchResultsView.as_view(), name='compare_results'),
    path('run_query/<search_id>', views.RunSearchView.as_view(), name='run_query'),
    path('owner/<slug:username>/project/<slug:project_slug>/<slug:search_slug>/history', views.HistoryView.as_view(), name='history_view'),
    path('analisys_outcome/<analisys_outcome_id>', views.ShowAnalisysOutcomeView.as_view(), name='analisys_outcome'),
    path('owner/<slug:username>/projects/', views.MyProjectsView.as_view(), name='my_projects'),
    path('search/', views.SearchView.as_view(), name='search'),
    # path('add_keyword/', views.AddKeywordView.as_view(), name='add_keyword'),

    path('goto/', views.GoToUrlView.as_view(), name='goto_url'),
]

searchr_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from searchr_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('searchR/', include('searchr_app.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('api/crawl/', views.CrawlerView.as_view(), name='crawler_view'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# This is required for static files while in development mode. (DEBUG=TRUE)
# No, not relevant to scrapy or crawling :)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchr_app/models/AnalisysOutcomePhraseValues.py
from django.db import models

from searchr_app.models import AnalisysOutcome


class AnalisysOutcomePhraseValues(models.Model):
    phrase_value = models.TextField()
    analisys_outcome = models.ForeignKey(AnalisysOutcome, on_delete=models.CASCADE, null=False)
    number_of_phrases = models.IntegerField(default=0)

    def __str__(self):
        return self.phrase_value

searchr_app/models/CrawlItem.py
import json

from django.db import models
from django.utils import timezone

from searchr_app.models import SearchResult, Search


class CrawlItem(models.Model):
    """
    Class representing scrapy crawl item with unique_id, extracted data, date and status.
    Only spiders from scrapy framework are inserting data into the table
    """
    unique_id = models.CharField(max_length=100, null=True)
    content_type = models.CharField(max_length=100, null=True)
    data = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=30, default='started')

    # Serialisation to return as JSON
    @property
    def to_dictionary(self):
        data = {
            'data': json.loads(self.data),
            'date': self.date,
            'content-type': self.content_type,
        }
        return data

    def __str__(self):
        return self.unique_id

    def save(self, *args, **kwargs):

        if self.status == 'finished':
            scrapy_id = self.unique_id
            search_result = SearchResult.objects.get(scrapy_unique_task_id=scrapy_id)

            if search_result is not None:
                search_result.status = SearchResult._FINISHED
                if self.content_type is not None:
                    search_result.content_type = self.content_type
                else:
                    search_result.content_type = 'SearchR-Unknown'
                if self.data is None or self.data == '':
                    self.data = 'Unable to find content for url: ' + search_result.url + '.'

                search_result.html_file = self.data
                search_result.search_result_hash = search_result.sha256_html_content()
                search_result.save()
                # update number of running searches in search
                search = Search.objects.get(id=search_result.search.id)
                search.running_results = search.running_results - 1
                search.save(force_update=True)

        super(CrawlItem, self).save(*args, **kwargs)

searchr_app/models/Phrase.py
from django.conf.global_settings import LANGUAGES
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from django.utils.text import slugify

from searchr_app.models import Project


class Phrase(models.Model):
    _PHRASE_PRIVATE_FIELD_NAME = 'Is Phrase private?'
    _PHRASE_MAX_LENGTH = 1024
    LANGUAGE_MAX_LENGTH = 7

    value = models.TextField(null=False, )
    date_created = models.DateTimeField(editable=False)
    date_last_searched = models.DateTimeField()
    number_of_searches = models.PositiveIntegerField(default=0)
    language = models.CharField(max_length=LANGUAGE_MAX_LENGTH, choices=LANGUAGES)
    # searches = models.ManyToManyField(
    #     Search,
    #     db_table='search_contains_phrase',
    # )
    projects = models.ManyToManyField(
        Project,
        db_table='project_contains_phrases',
    )
    slug = models.SlugField(max_length=_PHRASE_MAX_LENGTH, null=False, unique=False)

    def save(self, *args, **kwargs):
        if self.value == '':
            raise ValidationError('Value of phrase can not be empty')
        self.slug = slugify(self.value.strip())
        """ On save update timestamps """
        date_saved = timezone.now()
        if not self.id:
            self.date_created = date_saved
        self.date_last_searched = date_saved
        super(Phrase, self).save(*args, **kwargs)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name_plural = 'phrases'
        unique_together = ('value', 'language')

searchr_app/models/Search.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from searchr_app.models import Project


class Search(models.Model):
    """
    Search model represents single search object which has search parameters defined
    @:param str title: title of search. Has to be unique together in project
    """
    SEARCH_TITLE_LENGTH = 128
    SEARCH_ATTRIBS_LENGTH = 1024
    SEARCH_QUERY_LENGTH = 1024

    # _GOOGLE = 'go'
    _BING = 'bg'
    # _YAHOO = 'yh'
    SEARCH_ENGINE_CHOICES = [
        # (_GOOGLE, 'GOOGLE'),
        (_BING, 'BING'),
        # (_YAHOO, 'YAHOO'),
    ]

    _CREATED = 'created'
    _SEARCHED = 'searched'
    _RUNNING = 'running'
    SEARCH_STATUS_CHOICES = [
        (_CREATED, 'CREATED'),
        (_SEARCHED, 'SEARCHED'),
        (_RUNNING, 'RUNNING')
    ]

    title = models.CharField(max_length=SEARCH_TITLE_LENGTH, null=False, default=None)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=False)
    attributes = models.TextField(null=True)
    query = models.CharField(max_length=SEARCH_QUERY_LENGTH, null=False, default=None)
    search_engine = models.CharField(max_length=64, choices=SEARCH_ENGINE_CHOICES, default=_BING)
    date_created = models.DateTimeField(editable=False)
    phrases_list = models.TextField()
    status = models.CharField(max_length=64, null=False, blank=False, editable=False, default=_CREATED)
    running_results = models.IntegerField(null=False, default=0)
    slug = models.SlugField(max_length=SEARCH_TITLE_LENGTH, null=False, unique=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        is_new_search = False
        if not self.id:
            is_new_search = True
            self.date_created = timezone.now()
            self.slug = slugify(self.title.strip())
        if self.status == Search._RUNNING and self.running_results == 0:
            self.status = Search._SEARCHED
        super(Search, self).save(*args, **kwargs)
        if is_new_search:
            from searchr_app.models.search_models_helper_functions import create_search_history_item
            create_search_history_item(self, self.query, self.project.user.username)

    class Meta:
        verbose_name_plural = 'searches'
        unique_together = ('title', 'project')

searchr_app/models/SearchResult.py
from datetime import date

from django.db import models
from django.utils.timezone import now
from searchr_app.models import Search# , SearchHistory
from hashlib import sha256


class SearchResult(models.Model):
    SEARCH_RESULT_NAME_MAX_LEN = 128

    _CREATED = 'created'
    _STARTED = 'started'
    _FINISHED = 'finished'
    _FINISHED_SAVED = 'finished_saved'
    _FINISHED_ANALYZED = 'finished_analyzed'
    SEARCH_STATUS_CHOICES = [
        (_CREATED, 'CREATED'),
        (_STARTED, 'STARTED'),
        (_FINISHED, 'FINISHED'),
        (_FINISHED_SAVED, 'FINISHED_SAVED'),
        (_FINISHED_ANALYZED, 'ANALYZED')
    ]

    title = models.CharField(max_length=SEARCH_RESULT_NAME_MAX_LEN)
    url = models.URLField(null=False, blank=False)
    search_result_hash = models.CharField(max_length=SEARCH_RESULT_NAME_MAX_LEN)
    content_type = models.CharField(max_length=100, null=True)
    html_file = models.TextField(editable=False, null=True)
    date_found = models.DateTimeField()
    accuracy = models.FloatField(default=0)
    status = models.CharField(max_length=30, null=False, choices=SEARCH_STATUS_CHOICES, default=_CREATED)
    scrapy_unique_task_id = models.CharField(max_length=SEARCH_RESULT_NAME_MAX_LEN, editable=False)

    search = models.ForeignKey(Search, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        # Object Search Result is not editable
        is_new_result = False
        if not self.id:
            self.date_found = now()
            is_new_result = True
        # if self.status == self._FINISHED:
        #     self.status = self._FINISHED_SAVED
        #     self.search.running_results = self.search.running_results - 1
        #     self.search_result_hash = self.sha256_html_content()
        #     self.search.save()
        super(SearchResult, self).save(*args, **kwargs)
        if is_new_result:
            from searchr_app.models.search_models_helper_functions import add_result_to_history
            add_result_to_history(self.search, self)
        if self.status == self._FINISHED:
            # start analyzing result
            from searchr_app.models.search_models_helper_functions import analyze_search_result
            self.accuracy = analyze_search_result(self)
            self.set_status_to_analyzed()
            super(SearchResult, self).save(*args, **kwargs)

    def sha256_html_content(self):
        if self.html_file:
            hashed_html_content = sha256(str(self.html_file).encode('utf-8')).hexdigest()
        else:
            hashed_html_content = -1
        return hashed_html_content

    def set_status_to_analyzed(self):
        if not self.id:
            pass
        self.status = self._FINISHED_ANALYZED

    def __str__(self):
        return '[' + self.date_found.strftime("%d/%m/%Y, %H:%M:%S") + '] ' + self.title

    class Meta:
        verbose_name_plural = 'Search Results'
        verbose_name = 'Search Result'

searchr_app/forms/AdvancedPhraseForm.py
from django import forms
from django.conf.global_settings import LANGUAGES

from searchr_app.models import Phrase


class AdvancedPhraseForm(forms.ModelForm):
    value = forms.CharField(
        max_length=Phrase._PHRASE_MAX_LENGTH,
        required=True,
        widget=forms.Textarea(),
    )
    date_last_searched = forms.DateField(
        widget=forms.HiddenInput(),
        required=False,

    )
    date_created = forms.DateField(
        widget=forms.HiddenInput(),
        required=False,

    )
    number_of_searches = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False,
        initial=int(0),
    )
    language = forms.ChoiceField(
        choices=LANGUAGES,
    )
    projects = forms.MultipleChoiceField(
        widget=forms.HiddenInput(),
        required=False,
    )
    slug = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )

    class Meta:
        model = Phrase
        exclude = ['slug']

searchr_app/forms/ChooseResultForm.py
from django import forms

from searchr_app.models import SearchResult


class ChooseResultForm(forms.Form):

    search_results = forms.ModelChoiceField(
        help_text='Choose Search Result to compare',
        queryset=SearchResult.objects.all(),
        label='Choose Search Result to compare',
    )

    def __init__(self, *args, **kwargs):
        searchid = kwargs.pop('searchid', None)
        current_search_id = kwargs.pop('current_res_id', None)
        super(ChooseResultForm, self).__init__(*args, **kwargs)

        if searchid:
            self.fields['search_results'].queryset = SearchResult.objects.filter(search_id=searchid, status__in=[SearchResult._FINISHED, SearchResult._FINISHED_ANALYZED])
            if current_search_id:
                queryset = SearchResult.objects.filter(search_id=searchid,status__in=[SearchResult._FINISHED,SearchResult._FINISHED_ANALYZED]).exclude(id=current_search_id)
                self.fields['search_results'].queryset = queryset

searchr_app/forms/KeywordForm.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from searchr_app.models import Keyword


class KeywordForm(forms.ModelForm):
    keyword = forms.CharField(max_length=Keyword.KEYWORD_MAX_LENGTH, help_text="Please enter the keyword name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False, validators=[])

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model ( KeywordForm and Keyword )
        model = Keyword
        fields = ('keyword',)

    def clean_keyword(self):
        # Custom clean_<field_name>(self) method that validates field in the form
        keyword_keyword = self.cleaned_data['keyword']
        slug = slugify(keyword_keyword)

        if Keyword.objects.filter(slug=slug).exists():
            raise ValidationError('A keyword with that title already exists.')

        return keyword_keyword

searchr_app/forms/PhraseForm.py
from django import forms
from django.conf.global_settings import LANGUAGES
from django.core.exceptions import ValidationError

from searchr_app.models import Phrase, Keyword


class PhraseForm(forms.ModelForm):
    value = forms.CharField(
        label='Phrase value',
        max_length=Phrase._PHRASE_MAX_LENGTH,
        required=True,
        widget=forms.Textarea(attrs={'placeholder': 'Phrase value.'}),
        help_text='Enter phrase value',
    )
    date_last_searched = forms.DateField(
        widget=forms.HiddenInput(),
        required=False,

    )
    date_created = forms.DateField(
        widget=forms.HiddenInput(),
        required=False,

    )
    number_of_searches = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False,
        initial=int(0),
    )
    language = forms.ChoiceField(
        choices=LANGUAGES,
        initial='en',
    )
    projects = forms.MultipleChoiceField(
        widget=forms.HiddenInput(),
        required=False,
    )
    slug = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )

    class Meta:
        model = Phrase
        exclude = ['slug']

    def clean_value(self):
        # custom clean of value field to validate if words are not longer than 512 characters
        phrase_value = self.cleaned_data['value']
        words = phrase_value.split()
        for word in words:
            if len(word) > Keyword.KEYWORD_MAX_LENGTH:
                raise ValidationError("Phrase must contain keywords shorter than " + str(Keyword.KEYWORD_MAX_LENGTH) + ' characters.')
        return phrase_value

templates/searchr_app/add_phrase.html
{% extends 'searchr_app/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}



{% block title_block %}
    Add Phrase
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
        <h1 class="jumbotron-heading text-center">Add a Phrase</h1>
        </div>
    </div>

    <div class="container" style="background-color: #e4e7eb;">
        <div class="row">
            <div class="col-md-12 border border-dark rounded p-3">
                <form role="form" id="category_form" method="post" action="{% url 'searchr_app:add_phrase' %}">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            {{ form|as_crispy_errors }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8 mb-0">
                            {{ form.value|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8 mb-0">
                            {{ form.language|as_crispy_field }}
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit">Add Phrase</button>
                 </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/searchr_app/keywords.html
<ul class="nav flex-column">
    {% if keywords %}

        {% for k in keywords %}
            {% if k == current_keyword %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'searchr_app:show_keyword' k.slug %}"><span data-feather="arrow-right"></span>{{ k.keyword }}</a>
                </li>
            {% else %}
                <li><a href="{% url 'searchr_app:show_keyword' k.slug %}">{{ k.keyword }}</a></li>
            {% endif %}


        {% endfor %}
    {% else %}
        <li class="nav-item">There are no keywords present.</li>
    {% endif %}
</ul>

templates/searchr_app/show_search_result.html
{% extends 'searchr_app/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<style>
    #collapse1{
        overflow-y:scroll;
        height:200px;
    }
</style>

{% block title_block %}
    {% if search and user.is_authenticated %}
        Results of {{ search.title }}
    {% else %}
        Unknown Search Results
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if not user.is_authenticated or not search %}
        <div class="jumbotron p-4">
            <div class="container">
                    <h1 class="jumbotron-heading text-center">Specified Search Result does not exist<br/> or you are not logged in.</h1>
            </div>
        </div>
    {% else %}
        <div class="jumbotron p-4">
            <div class="container">
                    <nav aria-label="breadcrumb p-1">
                        <ol class="breadcrumb p-lg-0">
                            <li class="breadcrumb-item"><a href="{% url 'searchr_app:home' %}">Home</a> </li>
                            <li class="breadcrumb-item"><a href="{% url 'searchr_app:show_project' project.user.username project.slug %}">{{ project.title }}</a></li>
                            <li class="breadcrumb-item active"><a href="{% url 'searchr_app:show_search' project.user.username search.project.slug search.slug %}">{{ search.title }}</a> </li>
                            <li class="breadcrumb-item active"><a href="#">{{ search_result|safe }}</a></li>
                        </ol>
                    </nav>
                    <h3 class="jumbotron-heading text-center">Website title: {{ search_result.title|safe }}</h3>
                    <h5 class="jumbotron-content float-right text-left">
                        Project: <a href="{% url 'searchr_app:show_project' project.user.username project.slug %}">{{ project.title }}</a>
                    </h5>
                    <h5 class="jumbotron-content text-left">
                        Found in Search: <a href="{% url 'searchr_app:show_search' project.user.username search.project.slug search.slug %}">{{ search.title }}</a>
                    </h5>
                    <hr class="my-3">
                    <p>That page presents created <strong>Search Result</strong> object. You can find here parameters describing object, content of downloaded website.<br/> <strong>Table of Analysis outcome</strong> stores analysis results for specified Search Result.</p>
            </div>
        </div>
        <div class="container">
            <div class=" row h-20 mh-25">
                <div class="col-md-6 card border border-dark" style="background-color: lightsteelblue;">
                    <dl class="row p-0 card-text">
                        <dt class="col-sm-3 p-2">Search Result Title</dt>
                        <dd class="col-sm-9 p-2">{{ search_result.title|safe }}</dd>

                        <dt class="col-sm-3 p-2">URL Address</dt>
                        <dd class="col-sm-9 p-2">
                            <a href="{{ search_result.url }}">{{ search_result.url|safe }}</a>
                        </dd>

                        <dt class="col-sm-3 p-2">Accuracy</dt>
                        <dd class="col-sm-9 p-2">{{ search_result.accuracy|floatformat:3 }}</dd>

                        <dt class="col-sm-3 p-2">Content Type</dt>
                        <dd class="col-sm-9 p-2">{{ search_result.content_type|safe }}</dd>

                        <dt class="col-sm-3 p-2">Date found</dt>
                        <dd class="col-sm-9 p-2">{{ search_result.date_found }}</dd>

                        <dt class="col-sm-3 p-2">Status</dt>
                        <dd class="col-sm-9 p-2">{{ search_result.get_status_display|capfirst }}</dd>
                    </dl>
                </div>
                <div class="col-md-6 card border border-dark" style="background-color: lightsteelblue;">
                    <div class="card mb-6">

                            {% if analisys_results %}
                                <div class="card-header border border-primary" style="background-color: lightblue;">
                                    <h4 class="jumbotron-content">
                                        Search Result Analisys:
                                    </h4>
                                    <h6 class="jumbotron-content">
                                    Number of outcomes : {{ analisys_results.count }}
                                    </h6>
                                </div>
                                <div class="mh-20 card-body border border-dark p-2 overflow-auto">
                                    <div class="list-group p-0">
                                    <div class="panel-group">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h5 class="panel-title text-center">
                                                <a data-toggle="collapse" href="#collapse1">Table of Analysis Outcomes</a>
                                            </h5>
                                        </div>
                                        <div id="collapse1" class="panel-collapse collapse">
                                            <table class="table table-sm table-hover">
                                            <thead class="thead-dark">
                                            <tr class="table-row">
                                                <th class="table-cell p-1 border border-primary">Number of Phrases Found:</th>
                                                <th class="table-cell p-1 border border-primary">Is exact match?</th>
                                                <th class="table-cell p-1 border border-primary">Website part</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for a_res in analisys_results %}
                                                    <tr class="table-row">
                                                        <td class="table-cell p-1 border">
                                                            <a href="{% url 'searchr_app:analisys_outcome' a_res.id %}">
                                                                {% with a_res.analisysoutcomephrasevalues_set.all|first as item %}
                                                                    {{ item.number_of_phrases }}
                                                                {% endwith %}
{#                                                                ///{{ a_res.analisysoutcomephrasevalues_set.count }}#}
                                                            </a>
                                                        </td>
                                                        <td class="table-cell p-1 border">{{ a_res.exact_match }}</td>
                                                        <td class="table-cell p-1 border">{{ a_res.website_part }}</td>

                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        </div>
                                    </div>

                                    </div>

{#                                        {% for a_res in analisys_results %}#}
{#                                            <div class="list-group-item border border-dark ">#}
{#                                            <dl class="row p-0 card-text">#}
{#                                                <dt class="col-sm-3 p-1">Search Result Id:</dt>#}
{#                                                <dd class="col-sm-9 p-0">#}
{#                                                    <a href="{% url 'searchr_app:analisys_outcome' a_res.id %}">{{ a_res.id }}</a>#}
{#                                                </dd>#}
{##}
{#                                                <dt class="col-sm-3 p-1">Is exact match?</dt>#}
{#                                                <dd class="col-sm-9 p-0">#}
{#                                                    {{ a_res.exact_match }}#}
{#                                                </dd>#}
{##}
{#                                                <dt class="col-sm-3 p-1">Website part:</dt>#}
{#                                                <dd class="col-sm-9 p-0">{{ a_res.website_part }}</dd>#}
{#                                            </dl>#}
{#                                            </div>#}


{#                                        {% endfor %}#}
                                    </div>
                                </div>
                            {% else %}
                                <div class="card-header">
                                    <h3 class="jumbotron-content">
                                        Search Result Analisys:
                                    </h3>
                                    <h5 class="jumbotron-content">
                                    Number of outcomes : 0
                                    </h5>
                                </div>
                            {% endif %}

                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="codeModalLong" tabindex="-1" role="dialog" aria-labelledby="codeModalLongTitle" aria-hidden="true" >
          <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Content of {{ search_result.title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <p class="text-body">
                        <pre class="prettyprint linenums">
                            <code >
                                {{ search_result.html_file|escape }}

                            </code>
                        </pre>
                  </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <div class="container p-2">
                <form class="form" role="form" method="post" action="{% url 'searchr_app:search_result' search_result.id %}">
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    {{ form|as_crispy_errors }}
                    {{ form.search_results|as_crispy_field }}
                    <button class="btn btn-primary" type="submit" name="compare">Compare</button>
                </form>
        </div>
        <div class="container p-2">
            <h4 class="jumbotron-heading text-center">
                <p class="text-body">
                    Preview of downloaded content:
                </p>
            </h4>
            <p class="text-body">
                <pre class="prettyprint linenums">
                    <code >
                        {{ search_result.html_file|escape|truncatechars:1000 }}

                    </code>
                </pre>
            </p>
            <div class="container text-center">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#codeModalLong">
                    Show content
                </button>
            </div>
        </div>
    {% endif %}
{% endblock %}